#!/bin/bash

# Usage: AWS_start_stop_RDS.sh {start|stop}

case "$1" in
   start)
     #Get stopped RDS instances
     RDS_STOPPED_INSTANCES=$(aws rds describe-db-instances --query "DBInstances[?DBInstanceStatus=='stopped'].[DBInstanceIdentifier]" --output text | tr '\n' ' ') 
     if [ -n "$RDS_STOPPED_INSTANCES" ]
       then 
         RDS_STOPPED_INSTANCES_ARRAY=(${RDS_STOPPED_INSTANCES})
         for i in "${RDS_STOPPED_INSTANCES_ARRAY[@]}"
         do
           echo "Starting RDS instance: ${i}"
           AWS_OUTPUT=$(aws rds start-db-instance --db-instance-identifier ${i})
           echo "${AWS_OUTPUT}"  
         done
       else 
         echo "There are no stopped RDS instances"
     fi
     ;;     
   stop)
     #Get running RDS instances
     RDS_RUNNING_INSTANCES=$(aws rds describe-db-instances --query "DBInstances[?DBInstanceStatus=='available'].[DBInstanceIdentifier]" --output text | tr '\n' ' ') 
     if [ -n "$RDS_RUNNING_INSTANCES" ]
       then
         RDS_RUNNING_INSTANCES_ARRAY=(${RDS_RUNNING_INSTANCES})       
         for i in "${RDS_RUNNING_INSTANCES_ARRAY[@]}"
         do
           echo "Stopping RDS instance: ${i}"
           AWS_OUTPUT=$(aws rds stop-db-instance --db-instance-identifier ${i})
           echo "${AWS_OUTPUT}"  
         done       
       else
         echo "There are no running RDS instances"
     fi
     ;;
   *)	 
     echo "Usage: {start|stop}"
     exit 1
     ;;
esac



